services:

  pipeline:
    build: 
      context: .
      dockerfile: ./docker/pipeline/Dockerfile
    tty: true
    container_name: nuada-pipeline
    networks: 
      - backend
    secrets:
      - db-password
      - source-key-nyt
      - source-key-guardian
    environment:
      - SOURCE_KEY_NYT_FILE=/run/secrets/source-key-nyt
      - SOURCE_KEY_GUARDIAN_FILE=/run/secrets/source-key-guardian
      - DB_PWD_FILE=/run/secrets/db-password
      - DB_DIALECT=postgresql
      - DB_API=psycopg2
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=nuada
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: nuada-db
    networks: 
      - backend
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nuada
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  db_admin:
    image: dpage/pgadmin4
    container_name: nuada-db-admin
    networks:
      - backend
    restart: always
    secrets:
      - db-admin-password
    environment:
      - PGADMIN_DEFAULT_EMAIL=johnnyb1694@gmail.com
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/db-admin-password
    ports:
      - 8888:80
    volumes:
      - db-admin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

networks:
  backend:

volumes:
  db-data:
  db-admin-data:

secrets:
  db-admin-password:
    file: secrets/DB_ADMIN_PWD.txt
  db-password:
    file: secrets/DB_PWD.txt
  source-key-nyt:
    file: secrets/SOURCE_KEY_NYT.txt
  source-key-guardian:
    file: secrets/SOURCE_KEY_GUARDIAN.txt
