services:

  pipeline:
    build: 
      context: .
    tty: true
    networks: 
      - backend
    secrets:
      - db-password
      - source-key-nyt
    environment:
      - SOURCE_KEY_NYT_FILE=/run/secrets/source-key-nyt
      - DB_PWD_FILE=/run/secrets/db-password
      - DB_DIALECT=postgresql
      - DB_API=psycopg2
      - DB_USER=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=nuada
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    networks: 
      - backend
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nuada
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:

volumes:
  db-data:

secrets:
  db-password:
    file: secrets/DB_PWD.txt
  source-key-nyt:
    file: secrets/SOURCE_KEY_NYT.txt
