name: Deployment Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Configure dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Administer unit tests
        run: |
          pytest -v

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application to 'DigitalOcean'
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DEPLOYMENT_HOST}}
          username: ${{secrets.DEPLOYMENT_USER}}
          key: ${{secrets.DEPLOYMENT_KEY}}
          passphrase: ${{secrets.DEPLOYMENT_PASSPHRASE}}
          script: |
            echo 'Connection established successfully'